# Generated by Django 6.0.3 on 2026-03-04 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_dish_created_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='created',
        ),
        migrations.AddField(
            model_name='favorite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
